### ISSUE TITLE
Request: Is it possible to add a one-click harvest and one-click plant feature?

### ISSUE THREAD

**Issue by Tothesunrise** [FuelLabs/sway-farm#56] opened 2024-03-27 12:07 UTC
Request: Is it possible to add a one-click harvest and one-click plant feature? Doing it one by one is really too laborious.😔

**Comment by sarahschwartz** [comment] 2024-04-24 14:06
This is a duplicate of [issue #6](https://github.com/FuelLabs/sway-farm/issues/6)

**Closed by sarahschwartz** 2024-04-24 14:06 UTC
