### ISSUE TITLE
[Add one key sowing, one key harvesting function]

### ISSUE THREAD

**Issue by Swift-scouts** [FuelLabs/sway-farm#54] opened 2024-03-20 10:31 UTC
Each field needs to point seeding, and then wait for the wallet response, point confirmation, point harvest, and so on wallet response, the operation is too cumbersome

**Comment by sarahschwartz** [comment] 2024-04-24 14:09
This is a duplicate of [issue 6](https://github.com/FuelLabs/sway-farm/issues/6)

**Closed by sarahschwartz** 2024-04-24 14:09 UTC
